"""Autoregressive synthesis with the trained Keras TTS baseline (Griffin-Lim vocoder).

    python -m src.creation.keras_tts.synthesize --weights reports/tts_baseline/tts.weights.h5 \
        --out data/generated/keras_tts

Generates the >=10 varying-length prompts into <out>/*.wav. Quality is expected to be
rough (the point of the baseline).
"""
from __future__ import annotations

import argparse
import os

import numpy as np

from src.common.audio import save_wav
from src.creation.keras_tts.audio_tts import CFG, mel_to_wav
from src.creation.keras_tts.text import encode
from src.creation.keras_tts.model import build_model

PROMPTS = [
    "hello.",
    "good morning everyone.",
    "the quick brown fox jumps over the lazy dog.",
    "please call me back when you get a chance.",
    "artificial intelligence is changing the world.",
    "i would like a coffee with milk and no sugar.",
    "the meeting is scheduled for three o'clock tomorrow afternoon.",
    "she sells sea shells by the sea shore on a sunny day.",
    "in nineteen sixty nine, humans first walked on the moon.",
    "this is a synthetic voice generated by a neural network baseline.",
    "how much wood would a woodchuck chuck if a woodchuck could chuck wood?",
    "thank you for listening to this short demonstration of voice cloning.",
]


def synthesize_one(model, text: str, max_steps: int = 800, stop_thresh: float = 0.5) -> np.ndarray:
    import tensorflow as tf

    ids = tf.constant([encode(text)], dtype=tf.int32)
    memory = model.encoder(ids, training=False)
    model.cell._memory = memory
    model.cell._proc_memory = model.mem_dense(memory)

    h = tf.zeros((1, model.cell.units)); c = tf.zeros((1, model.cell.units))
    prev = tf.zeros((1, model.n_mels))
    frames = []
    for _ in range(max_steps):
        out, [h, c] = model.cell(prev, [h, c])
        mel_t = out[:, : model.n_mels]
        stop_t = tf.sigmoid(out[:, model.n_mels])
        frames.append(mel_t.numpy()[0])
        prev = mel_t
        if float(stop_t.numpy()[0]) > stop_thresh:
            break
    mel = np.asarray(frames, dtype=np.float32)[None]          # (1, T, n_mels)
    mel_post = mel + model.postnet(mel, training=False).numpy()
    return np.clip(mel_post[0], 0.0, 1.0)


def main() -> None:
    ap = argparse.ArgumentParser(description="Synthesize clips with the Keras TTS baseline.")
    ap.add_argument("--weights", required=True)
    ap.add_argument("--out", default="data/generated/keras_tts")
    # Parallel mode: synthesize the HELD-OUT transcripts instead of PROMPTS, so
    # MCD / log-mel SSIM can compare identical spoken content against the real
    # held-out audio. Output files are named by clip id to make pairing trivial.
    ap.add_argument("--texts-csv", help="LJSpeech metadata to speak instead of PROMPTS")
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)

    if args.texts_csv:
        from src.common.metadata import load_texts
        items = load_texts(args.texts_csv)
    else:
        items = [(f"kerastts_{i:02d}", t) for i, t in enumerate(PROMPTS)]

    model = build_model()
    # build variables with one dummy call, then load weights
    import tensorflow as tf
    _ = model((tf.zeros((1, 5), tf.int32), tf.zeros((1, 4, model.n_mels))), training=False)
    model.load_weights(args.weights)

    for i, (name, text) in enumerate(items):
        mel = synthesize_one(model, text)
        wav = mel_to_wav(mel, CFG)
        save_wav(os.path.join(args.out, f"{name}.wav"), wav, CFG.sr)
        print(f"[{i:02d}] {name} {text[:40]!r} -> {mel.shape[0]} frames")
    print(f"wrote {len(items)} clips -> {args.out}")


if __name__ == "__main__":
    main()
